{
  "formatVersion": "1.1",
  "component": {
    "group": "com.signerry.dss-android",
    "module": "dss-enumerations",
    "version": "1.02.08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "com.tom-roush",
          "module": "pdfbox-android",
          "version": {
            "requires": "2.0.27.0"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dss-enumerations-1.02.08.aar",
          "url": "dss-enumerations-1.02.08.aar",
          "size": 113402,
          "sha512": "d29702f1e3738ead7b3e2d60c1f9b760dca2fe3f0ac29254f83c84bf2a32e76c6acf19abb3313d0e3390777ed9b830a7cc452c7c3f3fc840bd43d892754ba88e",
          "sha256": "83113dbadd4a6294d2104dc2730a02d6a34cb4a45108e19cb1a234c95b9ed1aa",
          "sha1": "1547c4bca0c8b6ab183206d5253b32b366079bb8",
          "md5": "445c039cddd661a1a852cf6df766de6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.210"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.signerry.santuario",
          "module": "xmlsec",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "com.signerry",
          "module": "androidawt",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.1.6"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        },
        {
          "group": "com.signerry.dss-android",
          "module": "dss-android-compatibility",
          "version": {
            "requires": "1.02.08"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "com.tom-roush",
          "module": "pdfbox-android",
          "version": {
            "requires": "2.0.27.0"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dss-enumerations-1.02.08.aar",
          "url": "dss-enumerations-1.02.08.aar",
          "size": 113402,
          "sha512": "d29702f1e3738ead7b3e2d60c1f9b760dca2fe3f0ac29254f83c84bf2a32e76c6acf19abb3313d0e3390777ed9b830a7cc452c7c3f3fc840bd43d892754ba88e",
          "sha256": "83113dbadd4a6294d2104dc2730a02d6a34cb4a45108e19cb1a234c95b9ed1aa",
          "sha1": "1547c4bca0c8b6ab183206d5253b32b366079bb8",
          "md5": "445c039cddd661a1a852cf6df766de6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dss-enumerations-1.02.08-sources.jar",
          "url": "dss-enumerations-1.02.08-sources.jar",
          "size": 113475,
          "sha512": "838848f7d6d7ed502d6830e42c0eadd3f6259dc49e511cc8c689c2b5e0d21dbc7d7b62d81f4b64e94f2cedb473b926eaa43017ea4dd260ee0150645ac644a074",
          "sha256": "fdbb8d149c289d8efb9172f524cdf2ab6c89a375bfd36c51db7ce424b8709d1f",
          "sha1": "33f5ed392d59b3a2e9bf46c30253de5accd28d07",
          "md5": "85f33b3bbede50a0f629d22d79b71bea"
        }
      ]
    },
    {
      "name": "releaseTestFixturesVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.signerry.dss-android",
          "module": "dss-enumerations",
          "version": {
            "requires": "1.02.08"
          }
        }
      ],
      "files": [
        {
          "name": "dss-enumerations-1.02.08-test-fixtures.aar",
          "url": "dss-enumerations-1.02.08-test-fixtures.aar",
          "size": 761,
          "sha512": "69efd62250a1abbeeff8227d81cf33af69794c9ba222bbc1872640753823b07f228da7c0acf61ea811810f91e2172a1e3020663a25ef114a849287866bb76fbf",
          "sha256": "9194d8e6d0f244ecb4c594cb5c9d7bcca6eed2df87c7ca618f40f746c6885d2a",
          "sha1": "0cdd9d65e87a59957d7ef1be2db7d2e7a5576a02",
          "md5": "79f1e4f7da969a3fb6e4482519dd71d5"
        }
      ],
      "capabilities": [
        {
          "group": "com.signerry.dss-android",
          "name": "dss-enumerations-test-fixtures",
          "version": "unspecified"
        }
      ]
    },
    {
      "name": "releaseTestFixturesVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.signerry.dss-android",
          "module": "dss-enumerations",
          "version": {
            "requires": "1.02.08"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "dss-enumerations-1.02.08-test-fixtures.aar",
          "url": "dss-enumerations-1.02.08-test-fixtures.aar",
          "size": 761,
          "sha512": "69efd62250a1abbeeff8227d81cf33af69794c9ba222bbc1872640753823b07f228da7c0acf61ea811810f91e2172a1e3020663a25ef114a849287866bb76fbf",
          "sha256": "9194d8e6d0f244ecb4c594cb5c9d7bcca6eed2df87c7ca618f40f746c6885d2a",
          "sha1": "0cdd9d65e87a59957d7ef1be2db7d2e7a5576a02",
          "md5": "79f1e4f7da969a3fb6e4482519dd71d5"
        }
      ],
      "capabilities": [
        {
          "group": "com.signerry.dss-android",
          "name": "dss-enumerations-test-fixtures",
          "version": "unspecified"
        }
      ]
    }
  ]
}
