package zk

// Step 0 of docs/planning/EUDI-WALLET-POC-CONFORMANCE-PLAN.md §4: cross-verify the
// two ZK halves. The fixture under testdata/step0-rust-prover holds a proof made
// by ee_poa_demo over the Rust Longfellow runtime (the same one this package links
// through zkverify-ffi), so this test mostly re-verifies our own prover's output
// through the registry and the C ABI. That is the point: it pins the registry path
// end to end and gives the multipaz cross-check a same-runtime control. The proof
// the other half actually cares about is produced by multipaz 0.99.0 in the fork's
// :zk-conformance module and lands in testdata/step0-multipaz; when that directory
// exists, it is verified here too — this is the direction that can fail, because
// multipaz's libzkp.so is a Longfellow build this repository cannot name.

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/tomkabel/eudi-wallet-poc/verifier/go/circuits"
)

// fixture describes one directory holding a complete proof plus everything a
// verifier needs to check it.
type fixture struct {
	Version       uint32 `json:"version"`
	NumAttributes uint32 `json:"num_attributes"`
	PKx           string `json:"pkx"`
	PKy           string `json:"pky"`
	DocType       string `json:"doc_type"`
	Namespace     string `json:"namespace"`
	AttrID        string `json:"attr_id"`
	AttrCBORHex   string `json:"attr_cbor_hex"`
	Now           string `json:"now"`
}

func loadFixture(tb testing.TB, dir string) (Request, []byte) {
	tb.Helper()

	meta, err := os.ReadFile(filepath.Join(dir, "request.json"))
	if err != nil {
		tb.Fatalf("read request.json: %v", err)
	}
	var f fixture
	if err := json.Unmarshal(meta, &f); err != nil {
		tb.Fatalf("parse request.json: %v", err)
	}

	transcript, err := os.ReadFile(filepath.Join(dir, "transcript.bin"))
	if err != nil {
		tb.Fatalf("read transcript.bin: %v", err)
	}
	// The multipaz fixture names the timestamp "timestamp"; the Rust prover's
	// names it "now". They are the same input: the formatted string the proof
	// binds.
	now := f.Now
	if now == "" {
		var raw map[string]any
		if err := json.Unmarshal(meta, &raw); err != nil {
			tb.Fatalf("re-parse request.json: %v", err)
		}
		if ts, ok := raw["timestamp"].(string); ok {
			now = ts
		}
	}
	proof, err := os.ReadFile(filepath.Join(dir, "proof.bin"))
	if err != nil {
		tb.Fatalf("read proof.bin: %v", err)
	}
	attr, err := hex.DecodeString(f.AttrCBORHex)
	if err != nil {
		tb.Fatalf("parse attr_cbor_hex: %v", err)
	}

	req := Request{
		Version:       f.Version,
		NumAttributes: f.NumAttributes,
		PKx:           f.PKx,
		PKy:           f.PKy,
		DocType:       f.DocType,
		Namespace:     f.Namespace,
		AttrID:        f.AttrID,
		AttrCBOR:      attr,
		Now:           now,
		Transcript:    transcript,
		Proof:         proof,
	}
	return req, proof
}

// TestStep0RustProverFixture verifies the ee_poa_demo proof through Verify,
// checks it against the registry first (as EE-ZKP-023 requires of a relying
// party), and rejects a one-bit-flipped proof.
func TestStep0RustProverFixture(t *testing.T) {
	dir := "testdata/step0-rust-prover"
	req, proof := loadFixture(t, dir)

	reg, err := circuits.Load("../../circuits.json")
	if err != nil {
		t.Fatalf("load circuits.json: %v", err)
	}
	if _, err := CheckCircuit(reg, req.Version, req.NumAttributes); err != nil {
		t.Fatalf("registry must accept the fixture's circuit: %v", err)
	}

	if err := Verify(req); err != nil {
		t.Fatalf("ee_poa_demo proof did not verify: %v", err)
	}

	flipped := make([]byte, len(proof))
	copy(flipped, proof)
	flipped[len(flipped)/2] ^= 0x01
	req.Proof = flipped
	if err := Verify(req); err == nil {
		t.Fatal("a one-bit-flipped proof verified; the verifier is not checking anything")
	} else if !errors.Is(err, ErrInvalid) {
		t.Fatalf("flipped proof failed with the wrong error class: %v", err)
	}
}

// TestStep0MultipazFixture is the direction that can fail: a proof generated by
// multipaz 0.99.0's libzkp.so, verified by the Rust runtime this repository links.
// The fixture is written by the fork's :zk-conformance module (see
// testdata/step0-multipaz/GENERATED-BY for the command); when it is absent the test
// skips, because the two halves live in different checkouts.
func TestStep0MultipazFixture(t *testing.T) {
	dir := "testdata/step0-multipaz"
	if _, err := os.Stat(filepath.Join(dir, "proof.bin")); err != nil {
		if _, statErr := os.Stat(filepath.Join(dir, "GENERATED-BY")); statErr == nil {
			t.Fatalf("multipaz fixture was set up (%s exists) but proof.bin is missing; "+
				"the JVM run failed to write it", filepath.Join(dir, "GENERATED-BY"))
		}
		t.Skipf("no multipaz fixture at %s — run the fork's :zk-conformance "+
			"Step0CrossVerifyTest to generate it", dir)
	}

	req, _ := loadFixture(t, dir)

	reg, err := circuits.Load("../../circuits.json")
	if err != nil {
		t.Fatalf("load circuits.json: %v", err)
	}
	if _, err := CheckCircuit(reg, req.Version, req.NumAttributes); err != nil {
		t.Fatalf("multipaz proved under a circuit this registry does not list: %v", err)
	}

	if err := Verify(req); err != nil {
		t.Fatalf("multipaz proof did not verify under the Rust runtime: %v", err)
	}

	proof, err := os.ReadFile(filepath.Join(dir, "proof.bin"))
	if err != nil {
		t.Fatalf("read proof.bin: %v", err)
	}
	flipped := make([]byte, len(proof))
	copy(flipped, proof)
	flipped[len(flipped)/2] ^= 0x01
	req.Proof = flipped
	if err := Verify(req); err == nil {
		t.Fatal("a one-bit-flipped multipaz proof verified")
	} else if !errors.Is(err, ErrInvalid) {
		t.Fatalf("flipped multipaz proof failed with the wrong error class: %v", err)
	}
}
