package ee.cyber.wallet.zk

import java.io.File
import kotlinx.coroutines.test.runTest
import org.multipaz.cbor.Cbor
import org.multipaz.cbor.CborMap
import org.multipaz.cbor.DataItem
import org.multipaz.cbor.Simple
import org.multipaz.cbor.Tstr
import org.multipaz.cbor.buildCborArray
import org.multipaz.mdoc.response.DeviceResponse as MdocDeviceResponse
import org.multipaz.mdoc.response.buildDeviceResponse
import org.multipaz.mdoc.zkp.ProofVerificationFailureException
import org.multipaz.mdoc.zkp.longfellow.LongfellowZkSystem
import kotlin.test.Test
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Step 8.7 fixture for ee-eudiw's OpenID4VP `mso_mdoc_zk` verifier
 * (docs/planning/EUDI-WALLET-POC-CONFORMANCE-PLAN.md §8.7): a `DeviceResponse`
 * carrying `zkDocuments` whose proof binds the **B.2.6.1 OpenID4VPHandover**
 * session transcript —
 *
 *     SessionTranscript = [null, null, OpenID4VPHandover]
 *     OpenID4VPHandover = ["OpenID4VPHandover", Sha256(OpenID4VPHandoverInfoBytes)]
 *     OpenID4VPHandoverInfoBytes = bstr .cbor [clientId, nonce, jwkThumbprint, responseUri]
 *
 * written exactly as ee-eudiw's oid4vp.SessionTranscript builds it, with the
 * fixed handover parameters recorded in `request.json` so the Go test can
 * re-derive the bytes from the session rather than trusting the fixture. The
 * step 2a fixture binds a different, synthetic transcript
 * (SessionTranscripts.forZkConformance, not the ISO 18013-7 Annex C dcapi
 * one); a proof bound here must NOT verify over it — that is the second
 * assertion in this test.
 *
 * Run: (cd eudi-wallet-poc && ANDROID_HOME=/opt/android-sdk ./gradlew
 * :zk-conformance:test --tests 'ee.cyber.wallet.zk.Step87OpenID4VPFixtureTest' --offline)
 * The ee-eudiw checkout defaults to a sibling directory; override it with
 * `-Dstep0.eeEudiw=...`.
 */
class Step87OpenID4VPFixtureTest {

    /** The handover parameters the fixture proof binds. Go re-derives the transcript from them. */
    private val clientId = "https://verifier.example.com"
    private val nonce = "step87-openid4vp-nonce-0123456789abcdef"
    private val responseUri = "https://verifier.example.com/present/response/step87"

    @Test
    fun writeOpenID4VPZkFixtureForGoVerifier() = runTest {
        val eeEudiw = EeEudiw.assumePresent()
        val zkSystem = LongfellowZkSystem().apply { addDefaultCircuits() }

        val sessionTranscript = openid4vpSessionTranscript()
        val signedAt = ZkConformanceConsts.signedAtNow()
        val minted = MdocMinter.mintAgeVerificationMdoc(sessionTranscript, signedAt)
        val spec = ZkConformanceSpecs.oneAttributeSpec(zkSystem)
        val zkDocument = zkSystem.generateProof(spec, minted.document, sessionTranscript, signedAt)

        // Self-check first: the proof must verify against the SAME transcript
        // it was generated over.
        zkSystem.verifyProof(zkDocument, spec, sessionTranscript)
        assertTrue(zkDocument.proof.size > 0, "prover returned an empty proof")

        // And must NOT verify against the step 2a fixture's synthetic
        // transcript, which the Go test's negative control reads: if the two
        // bindings were interchangeable, that control would mean nothing.
        assertFailsWith<ProofVerificationFailureException>(
            "a proof bound to the OpenID4VP handover verified against the step 2a transcript"
        ) {
            zkSystem.verifyProof(zkDocument, spec, SessionTranscripts.forZkConformance())
        }

        val deviceResponse = buildDeviceResponse(
            sessionTranscript,
            MdocDeviceResponse.STATUS_OK
        ) {
            addZkDocument(zkDocument)
        }.toDataItem()
        val bytes = Cbor.encode(deviceResponse)

        val dir = File(eeEudiw, "verifier/go/zk/testdata/step8-7-openid4vp-zk")
        dir.mkdirs()
        File(dir, "device_response.cbor").writeBytes(bytes)
        File(dir, "device_response_issuer.json").writeText(trustStoreJson(minted))
        // attr_cbor_hex f5 is CBOR true, the age_over_18 value MdocMinter mints.
        File(dir, "request.json").writeText(
            """
            {
              "client_id": "$clientId",
              "nonce": "$nonce",
              "response_uri": "$responseUri",
              "jwk_thumbprint": null,
              "doc_type": "${ZkConformanceConsts.AV_DOCTYPE}",
              "namespace": "${ZkConformanceConsts.AV_NAMESPACE}",
              "attr_id": "${ZkConformanceConsts.AGE_OVER_18}",
              "attr_cbor_hex": "f5",
              "timestamp": "${ZkConformanceFormat.formatDate(signedAt)}",
              "version": ${spec.getParam<Long>("version")},
              "num_attributes": ${spec.getParam<Long>("num_attributes")},
              "zk_system_spec_id": "${spec.id}"
            }
            """.trimIndent()
        )
        File(dir, "GENERATED-BY").writeText(
            "Generated by eudi-wallet-poc :zk-conformance Step87OpenID4VPFixtureTest\n" +
                "fork commit: ${forkCommit()}\n" +
                "multipaz: 0.99.0 (org.multipaz:multipaz-longfellow-jvm)\n" +
                "transcript: B.2.6.1 OpenID4VPHandover over client_id/nonce/response_uri in request.json\n" +
                "  (jwk_thumbprint null - direct_post, not direct_post.jwt)\n" +
                "shape: DeviceResponse.Builder(addZkDocument).toDataItem() with zkDocuments\n" +
                "files: device_response.cbor, device_response_issuer.json, request.json\n" +
                "command: (cd eudi-wallet-poc && ANDROID_HOME=/opt/android-sdk ./gradlew\n" +
                "  :zk-conformance:test --tests\n" +
                "  'ee.cyber.wallet.zk.Step87OpenID4VPFixtureTest' --offline)\n" +
                "consumed by: ee-eudiw verifier/go/zk TestStep87OpenID4VPZkVerify\n"
        )

        // Sanity: the map carries the top-level zkDocuments key.
        val decoded = Cbor.decode(bytes) as CborMap
        assertTrue(
            decoded.items.keys.any { it is Tstr && it.value == "zkDocuments" },
            "fixture has no top-level zkDocuments"
        )
        println("step8.7: wrote OpenID4VP mso_mdoc_zk fixture (${bytes.size} bytes, proof " +
            "${zkDocument.proof.size} bytes) to ${dir.absolutePath}")
    }

    /**
     * OpenID4VP 1.0 Appendix B.2.6.1, hand-rolled to byte-match ee-eudiw's
     * `oid4vp.SessionTranscript`:
     * deterministic-length CBOR heads, sha-256 of the handover info bytes.
     */
    private fun openid4vpSessionTranscript(): DataItem {
        // OpenID4VPHandoverInfo = [clientId, nonce, jwkThumbprint, responseUri],
        // jwkThumbprint null for direct_post.
        val info = buildCborArray {
            add(clientId)
            add(nonce)
            add(Simple.NULL)
            add(responseUri)
        }
        val infoBytes = Cbor.encode(info)
        val digest = java.security.MessageDigest.getInstance("SHA-256").digest(infoBytes)

        // SessionTranscript = [null, null, ["OpenID4VPHandover", bstr(digest)]]
        return buildCborArray {
            add(Simple.NULL)
            add(Simple.NULL)
            add(
                buildCborArray {
                    add("OpenID4VPHandover")
                    add(digest)
                }
            )
        }
    }
}
