package ee.cyber.wallet.zk

import java.io.File
import kotlinx.coroutines.test.runTest
import org.multipaz.cbor.Cbor
import org.multipaz.cbor.CborMap
import org.multipaz.cbor.Tstr
import org.multipaz.mdoc.response.DeviceResponse as MdocDeviceResponse
import org.multipaz.mdoc.response.buildDeviceResponse
import org.multipaz.mdoc.zkp.longfellow.LongfellowZkSystem
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Step 2a fixture for ee-eudiw's ISO 18013-7 Annex C verifier
 * (docs/planning/STEP2A-RECORD.md, PENDING-DEVICE item 4): a complete
 * `DeviceResponse` exactly as the wallet sends it —
 * `buildDeviceResponse(...) { addZkDocument(it) }.toDataItem()`, the same
 * serialization as DigitalCredentialsViewModel.zkDeviceResponse — written raw
 * into ee-eudiw's `verifier/go/zk/testdata/step2a-iso-annex-c/device_response.cbor`.
 *
 * The embedded ZkDocument is produced by generateProof exactly as in
 * Step0CrossVerifyTest (same minted mdoc, same session-transcript shape) and
 * self-verified before it leaves this test, so the Go side can prove the whole
 * path end to end: ParseZkDocuments -> spec allowlist -> zk.Verify.
 *
 * Run: (cd eudi-wallet-poc && ANDROID_HOME=/opt/android-sdk ./gradlew
 * :zk-conformance:test --tests 'ee.cyber.wallet.zk.Step2aDeviceResponseFixtureTest' --offline)
 */
class Step2aDeviceResponseFixtureTest {

    @Test
    fun writeDeviceResponseFixtureForGoVerifier() = runTest {
        val eeEudiw = EeEudiw.assumePresent()
        val zkSystem = LongfellowZkSystem().apply { addDefaultCircuits() }

        val sessionTranscript = SessionTranscripts.forZkConformance()
        val signedAt = ZkConformanceConsts.signedAtNow()
        val minted = MdocMinter.mintAgeVerificationMdoc(sessionTranscript, signedAt)
        val spec = ZkConformanceSpecs.oneAttributeSpec(zkSystem)
        val zkDocument = zkSystem.generateProof(spec, minted.document, sessionTranscript, signedAt)

        // Self-check first: if this fails, the fixture is bad before the Go
        // side ever sees it.
        zkSystem.verifyProof(zkDocument, spec, sessionTranscript)
        assertTrue(zkDocument.proof.size > 0, "prover returned an empty proof")

        val deviceResponse = buildDeviceResponse(
            sessionTranscript,
            MdocDeviceResponse.STATUS_OK
        ) {
            addZkDocument(zkDocument)
        }.toDataItem()
        val bytes = Cbor.encode(deviceResponse)

        val dir = File(eeEudiw, "verifier/go/zk/testdata/step2a-iso-annex-c")
        dir.mkdirs()
        File(dir, "device_response.cbor").writeBytes(bytes)
        File(dir, "device_response_transcript.bin").writeBytes(Cbor.encode(sessionTranscript))
        File(dir, "device_response_issuer.json").writeText(trustStoreJson(minted))
        File(dir, "device_response_GENERATED-BY").writeText(
            "Generated by eudi-wallet-poc :zk-conformance Step2aDeviceResponseFixtureTest\n" +
                "multipaz: 0.99.0 (org.multipaz:multipaz-longfellow-jvm)\n" +
                "shape: DeviceResponse.Builder(addZkDocument).toDataItem() - the same\n" +
                "  serialization as DigitalCredentialsViewModel.zkDeviceResponse\n" +
                "files: device_response.cbor (the response), device_response_transcript.bin\n" +
                "  (the session transcript the proof binds)\n" +
                "command: (cd eudi-wallet-poc && ANDROID_HOME=/opt/android-sdk ./gradlew\n" +
                "  :zk-conformance:test --tests\n" +
                "  'ee.cyber.wallet.zk.Step2aDeviceResponseFixtureTest' --offline)\n" +
                "consumed by: ee-eudiw verifier/go TestStep2aMultipazDeviceResponse\n"
        )

        // Sanity: the map carries the top-level zkDocuments key (the shape the
        // old parser did not look at).
        val decoded = Cbor.decode(bytes) as CborMap
        assertTrue(
            decoded.items.keys.any { it is Tstr && it.value == "zkDocuments" },
            "fixture has no top-level zkDocuments"
        )
        println("step2a: wrote DeviceResponse fixture (${bytes.size} bytes, proof " +
            "${zkDocument.proof.size} bytes) to ${dir.absolutePath}")
    }
}

/**
 * The minted issuer's public half as the Go test's trust store names it
 * (oid4vp.LoadTrustStore: 0x-prefixed pkx/pky). The Go test copies this into
 * its trust store the way a relying party enrolls a real issuer.
 */
private fun trustStoreJson(minted: MintedMdoc): String {
    // X509Cert.ecPublicKey returns the double-coordinate form for P-256 keys,
    // whose x/y are already unsigned fixed-width field bytes.
    val pk = minted.issuerCert.ecPublicKey as org.multipaz.crypto.EcPublicKeyDoubleCoordinate
    val xHex = pk.x.joinToString("") { "%02x".format(it) }
    val yHex = pk.y.joinToString("") { "%02x".format(it) }
    return "{\"issuers\":[{\"name\":\"EE-EUDIW demo issuer (multipaz fixture)\"," +
        "\"doc_type\":\"${ZkConformanceConsts.AV_DOCTYPE}\"," +
        "\"namespace\":\"${ZkConformanceConsts.AV_NAMESPACE}\"," +
        "\"pkx\":\"0x$xHex\",\"pky\":\"0x$yHex\"}]}"
}
